---
- ansible.posix.selinux:
    policy: targeted
    state: enforcing

- community.general.sefcontext:
    target: "{{ redis_dir }}(/.*)?"
    setype: var_lib_t
    state: present

- command: "restorecon -Rv {{ redis_dir }}"
  changed_when: false

- community.general.sefcontext:
    target: "{{ redis_etc_dir }}(/.*)?"
    setype: etc_t 
    state: present

- command: "restorecon -Rv {{ redis_etc_dir }}"
  changed_when: false
