redis_port: 6379
sentinel_port: 26379

redis_requirepass: "Str0ngRedisPass!"
redis_masterauth: "Str0ngRedisPass!"
sentinel_auth_pass: "Str0ngRedisPass!"

redis_master_host: "SYSVMTCRXRDSM7"
redis_quorum: 2
failover_timeout_ms: 10000

redis_conf_path: /etc/redis.conf
sentinel_conf_path: /etc/redis-sentinel.conf
redis_dir: /var/lib/redis
redis_etc_dir: /etc/redis
redis_log: /var/log/redis/redis.log
sentinel_log: /var/log/redis/redis-sentinel.log
redis_user: redis
redis_group: redis

overcommit_memory: 1
transparent_hugepage: "never"

redis_service_name: redis
sentinel_service_name: redis-sentinel

allowed_redis_clients_cidr: "10.0.0.0/24"
allowed_cluster_cidr: "10.1.186.0/24"

redis_use_tls: true

# Keep existing plain port for Sentinel/replication
redis_port: 6379

# New TLS port for clients
redis_tls_port: 6380

# Where TLS files will live on the Redis nodes
redis_tls_dir: /etc/redis/tls
redis_tls_cert_file: "abk-wildcard.crt"
redis_tls_key_file: "abk-wildcard.key"
redis_tls_ca_file: "ca-abk.crt"
redis_requirepass: "Str0ngRedisPass!"   # or set your password here
redis_tls_auth_clients: "yes"  # "yes" if you want client cert auth

